version: '3.8'

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    network_mode: "host"
    environment:
      - XMPP_DOMAIN=isc-coordinator.lan
      - XMPP_USERNAME=alberto-ctrl
      - XMPP_PASSWORD=plsnohack 
